services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blockchainNetwork
  mongo-express:
    image: mongo-express
    container_name: mongo-admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: ""
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
    depends_on:
      - mongo
    networks:
      - blockchainNetwork


  backend:
    build: ./backend
    container_name: node-app
    ports:
      - "3000:3000"    
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/blockchain
    networks:
      - blockchainNetwork

  frontend:
    build: ./frontend
    container_name: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - blockchainNetwork

volumes:
  mongo_data:
networks:
  blockchainNetwork:
